basePath: /
definitions:
  dto.HealthResponse:
    properties:
      service:
        example: redirect-service
        type: string
      status:
        example: UP
        type: string
      version:
        example: 1.0.0
        type: string
    type: object
  dto.RedirectResponse:
    properties:
      originalUrl:
        example: https://example.com
        type: string
    type: object
  dto.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
host: localhost:3011
info:
  contact:
    email: support@repath.com
    name: API Support
  description: |-
    A high-performance URL shortening and redirect service built with Go, Gin, MongoDB, and Redis.
    This service provides URL shortening, custom aliases, and redirect functionality.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Re:Path Redirect Service API
  version: "1.0"
paths:
  /api/info/{shortCode}:
    get:
      parameters:
      - description: Short Code
        in: path
        name: shortCode
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get URL information
      tags:
      - Redirect
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.HealthResponse'
              type: object
      summary: Health check
      tags:
      - Health
  /r/{shortCode}:
    get:
      consumes:
      - application/json
      description: Returns the original URL information without performing a redirect
      parameters:
      - description: Short Code
        in: path
        name: shortCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RedirectResponse'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get original URL from short code
      tags:
      - Redirect
schemes:
- http
- https
swagger: "2.0"
