basePath: /
definitions:
  domain.StatLink:
    properties:
      clicks:
        type: integer
      date:
        type: string
    type: object
  domain.TopLink:
    properties:
      clicks:
        type: integer
      original_url:
        type: string
      short_url:
        type: string
      status:
        type: boolean
    type: object
  dto.DashboardResponse:
    properties:
      stat_links:
        items:
          $ref: '#/definitions/domain.StatLink'
        type: array
      top_links:
        items:
          $ref: '#/definitions/domain.TopLink'
        type: array
      total_click:
        example: 333
        type: integer
      total_link:
        example: 666
        type: integer
      uniq_visitors:
        example: 2
        type: integer
    type: object
  dto.HealthResponse:
    properties:
      service:
        example: redirect-service
        type: string
      status:
        example: UP
        type: string
      version:
        example: 1.0.0
        type: string
    type: object
  dto.RedirectResponse:
    properties:
      originalUrl:
        example: https://example.com
        type: string
    type: object
  dto.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
host: localhost:3011
info:
  contact:
    email: support@repath.com
    name: API Support
  description: |-
    A high-performance URL shortening and redirect service built with Go, Gin, MongoDB, and Redis.
    This service provides URL shortening, custom aliases, and redirect functionality.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Re:Path Redirect Service API
  version: "1.0"
paths:
  /api/dashboard:
    get:
      consumes:
      - application/json
      description: Get dashboard statistics (requires authentication)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.DashboardResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: Get dashboard statistics
      tags:
      - Dashboard
  /api/info/{shortUrl}:
    get:
      parameters:
      - description: Short Url
        in: path
        name: shortCode
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get URL information
      tags:
      - Redirect
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.HealthResponse'
              type: object
      summary: Health check
      tags:
      - Health
  /r/{shortUrl}:
    get:
      consumes:
      - application/json
      description: Returns the original URL information without performing a redirect
      parameters:
      - description: Short Url
        in: path
        name: shortUrl
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RedirectResponse'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get original URL from short url
      tags:
      - Redirect
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
