// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hoggir/re-path/redirect-service/internal/config"
	"github.com/hoggir/re-path/redirect-service/internal/database"
	"github.com/hoggir/re-path/redirect-service/internal/handler"
	"github.com/hoggir/re-path/redirect-service/internal/repository"
	"github.com/hoggir/re-path/redirect-service/internal/server"
	"github.com/hoggir/re-path/redirect-service/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*server.Server, error) {
	configConfig := config.Load()
	mongoDB, err := database.NewMongoDB(configConfig)
	if err != nil {
		return nil, err
	}
	urlRepository := repository.NewURLRepository(mongoDB)
	redis, err := database.NewRedis(configConfig)
	if err != nil {
		return nil, err
	}
	cacheService := service.NewCacheService(redis, configConfig)
	redirectService := service.NewRedirectService(urlRepository, cacheService, configConfig)
	clickEventRepository := repository.NewClickEventRepository(mongoDB)
	geoIPService := service.NewGeoIPService(cacheService, configConfig)
	clickEventService := service.NewClickEventService(clickEventRepository, geoIPService, redirectService)
	rabbitMQ, err := database.NewRabbitMQ(configConfig)
	if err != nil {
		return nil, err
	}
	rabbitMQRPCService := service.NewRabbitMQRPCService(rabbitMQ)
	dashboardService := service.NewDashboardService(rabbitMQRPCService, cacheService, configConfig)
	redirectHandler := handler.NewRedirectHandler(redirectService, clickEventService, dashboardService)
	healthHandler := handler.NewHealthHandler()
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	handlers := server.NewHandlers(redirectHandler, healthHandler, dashboardHandler)
	jwtService := service.NewJWTService(configConfig)
	middlewares := server.NewMiddlewares(configConfig, jwtService)
	serverServer := server.New(configConfig, handlers, middlewares, mongoDB, redis)
	return serverServer, nil
}
