// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hoggir/re-path/redirect-service/internal/config"
	"github.com/hoggir/re-path/redirect-service/internal/database"
	"github.com/hoggir/re-path/redirect-service/internal/handler"
	"github.com/hoggir/re-path/redirect-service/internal/repository"
	"github.com/hoggir/re-path/redirect-service/internal/server"
	"github.com/hoggir/re-path/redirect-service/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*server.Server, error) {
	configConfig := config.Load()
	mongoDB, err := database.NewMongoDB(configConfig)
	if err != nil {
		return nil, err
	}
	urlRepository := repository.NewURLRepository(mongoDB)
	redis, err := database.NewRedis(configConfig)
	if err != nil {
		return nil, err
	}
	redirectService := service.NewRedirectService(urlRepository, redis, configConfig)
	redirectHandler := handler.NewRedirectHandler(redirectService)
	healthHandler := handler.NewHealthHandler()
	serverServer := server.New(configConfig, redirectHandler, healthHandler, mongoDB, redis)
	return serverServer, nil
}
