// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/hoggir/re-path/redirect-service/internal/app/http"
	"github.com/hoggir/re-path/redirect-service/internal/app/http/handler"
	"github.com/hoggir/re-path/redirect-service/internal/app/repository"
	"github.com/hoggir/re-path/redirect-service/internal/app/service"
)

// Injectors from wire.go:

func InitializeApp() *gin.Engine {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	engine := http.NewRouter(userHandler)
	return engine
}
